django_level_four/django_level_four/urls.py
from django.contrib import admin
from django.urls import path,include
from django.urls import re_path as url
from learning_templates import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    path('admin/', admin.site.urls),
    url('',include('learning_templates.urls'))
]

django_level_four/learning_templates/urls.py
from django.contrib import admin
from django.urls import path,include
from learning_templates import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import re_path as url
from .views import *

app_name='learning_templates'

urlpatterns = [
    
    url(r'^relative_templates/$',views.url_templates,name='relative_templates'),
    url(r'^other/$',views.other,name='other'),

    
    
]

django_level_four/newproject/myapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home,name='home')
]

django_level_four/newproject/newproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]

django_level_four/learning_templates/models.py
from django.db import models

# Create your models here.

django_level_four/newproject/myapp/models.py
from django.db import models

# Create your models here.

django_level_four/learning_templates/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    context_dict= {'name':'hello worl', 'number':100}
    return render(request,'basic_app/index.htm',context_dict)

def other(request):
    return render(request,'basic_app/other.htm')

def url_templates(request):
    return render(request,'basic_app/relative_url_templates.htm')

django_level_four/newproject/myapp/views.py
from django.shortcuts import render,HttpResponse

# Create your views here.
def home(request):
    return render(request, 'home.html')

def result(request):
    # return render(request, 'home.html')
    no1= int(request.GET.get('no1'))
    no2= int(request.GET.get('no2'))

    answer = no1 + no2

    return render (request, 'result.html',{ 'answer' : answer})

django_level_four/newproject/templates/home.html
<h2>Welcome</h2>

<form action="result">
    <input type="number" name="no1">
    <input type="number" name="no2">

    <input type="submit" >

</form>

django_level_four/newproject/templates/result.html
{{answer}}

django_level_four/templates/basic_app/base.htm
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link  href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>

    <!-- <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li class="navbar-brand"><a href="#">Brand</a></li>
                <li class="navbar-link"><a href="#">Admin</a></li>
                <li class="navbar-link"><a href="#">Other</a></li>

            </ul>

        </div>

    </nav> -->

    <nav class="navbar navbar-default navbar-static-top">

        <div class="container">
          <!-- Links -->
          <ul class="navbar-nav">
            <li class="nav-brand">
              <a class="nav-link" href="#">Brand</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#"">Other</a>
            </li>
           
          </ul>
        </div>
      
      </nav> 


    <div class="container">
        {% block body_block%}
        {% endblock %}

    </div>
    
</body>
</html>

django_level_four/templates/basic_app/index.htm
<!DOCTYPE html>
{% extends "basic_app/base.htm"%}
{% block body_block%}
<h1>Welcome to Index</h1>
<h2> This is a index page</h2>
{{ name|upper}}
{{ number|add:99}}
{% endblock %}

django_level_four/templates/basic_app/other.htm
<!DOCTYPE html>

{% extends "basic_app/base.htm"%}
{% block body_block%}
<h1>Welcome to Other</h1>
<h2> This is a example for inheriting</h2>
{% endblock %}

    

django_level_four/templates/basic_app/relative_url_templates.htm
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>

    <h1>Welcome to Relative url tempplates</h1>
    <a href="{% url 'learning_templates:other' %}">Go To Other Page</a>
    <a href="{% url 'admin:index' %}">Go To Admin</a>
    <a href="{% url 'index' %}">Go To Index</a>
    
</body>
</html>